export const MATRIX_POLICIES = {
  version: "1.1.0",
  stages: {
    discover: {
      maxAttemptsTotal: 3,
      maxAttemptsPerFamily: 2,
      forceFamilySwitchErrorKinds: [
        "cli_not_found",
        "auth_or_permission",
        "model_unavailable",
        "token_limit",
        "provider_bad_request",
      ],
      fallbackOrder: ["teddy-gpt-oss", "codex-exec", "teddy-default"],
      fallbackOrderOnFamilySwitch: ["codex-exec", "teddy-gpt-oss", "teddy-default"],
      nonzeroExitRetry: {
        enabled: false,
        errorKind: "nonzero_exit",
      },
      strategies: [
        {
          id: "teddy-default",
          name: "teddy default",
          family: "teddy",
          toolId: "tool.discovery.teddy.default",
        },
        {
          id: "teddy-gpt-oss",
          name: "teddy gpt-oss-120b",
          family: "teddy",
          toolId: "tool.discovery.teddy.gpt_oss",
        },
        {
          id: "codex-exec",
          name: "codex exec",
          family: "codex",
          toolId: "tool.discovery.codex.exec",
        },
      ],
      matrix: {
        cli_not_found: ["codex-exec"],
        auth_or_permission: ["codex-exec"],
        model_unavailable: ["teddy-gpt-oss", "codex-exec"],
        token_limit: ["codex-exec", "teddy-gpt-oss"],
        rate_limited: ["teddy-gpt-oss", "codex-exec"],
        timeout: ["teddy-gpt-oss", "codex-exec"],
        provider_bad_request: ["codex-exec", "teddy-gpt-oss"],
        nonzero_exit: ["teddy-gpt-oss", "codex-exec"],
        unknown: ["teddy-gpt-oss", "codex-exec"],
      },
    },
    plan: {
      maxAttemptsTotal: 3,
      maxAttemptsPerFamily: 2,
      maxRecursionDepth: 2,
      maxRecursiveBranches: 3,
      qualityPassThreshold: 75,
      forceFamilySwitchErrorKinds: ["auth_or_permission", "cli_not_found"],
      fallbackOrder: ["codex-recursive", "teddy-direct", "codex-direct"],
      fallbackOrderOnFamilySwitch: ["teddy-direct", "codex-recursive", "codex-direct"],
      nonzeroExitRetry: {
        enabled: true,
        errorKind: "nonzero_exit",
      },
      strategies: [
        {
          id: "codex-direct",
          name: "codex direct",
          family: "direct",
          toolId: "tool.plan.codex.direct",
        },
        {
          id: "codex-recursive",
          name: "codex recursive",
          family: "recursive",
          toolId: "tool.plan.codex.recursive",
        },
        {
          id: "teddy-direct",
          name: "teddy direct",
          family: "alt_model",
          toolId: "tool.plan.teddy.direct",
        },
      ],
      matrix: {
        quality_low: ["codex-recursive", "teddy-direct"],
        invalid_output: ["codex-recursive", "teddy-direct"],
        token_limit: ["codex-recursive", "teddy-direct"],
        timeout: ["codex-recursive", "teddy-direct"],
        rate_limited: ["teddy-direct", "codex-recursive"],
        model_unavailable: ["teddy-direct", "codex-recursive"],
        provider_bad_request: ["codex-recursive", "teddy-direct"],
        auth_or_permission: ["teddy-direct", "codex-recursive"],
        cli_not_found: ["teddy-direct", "codex-recursive"],
        nonzero_exit: ["codex-recursive", "teddy-direct"],
        unknown: ["codex-recursive", "teddy-direct"],
      },
    },
    code: {
      maxAttemptsTotal: 3,
      maxAttemptsPerFamily: 2,
      forceFamilySwitchErrorKinds: ["auth_or_permission", "cli_not_found"],
      fallbackOrder: ["codex-exec-patch", "teddy-exec", "codex-exec"],
      fallbackOrderOnFamilySwitch: ["teddy-exec", "codex-exec-patch", "codex-exec"],
      nonzeroExitRetry: {
        enabled: true,
        errorKind: "nonzero_exit",
      },
      strategies: [
        {
          id: "codex-exec",
          name: "codex exec",
          family: "codex",
          toolId: "tool.code.codex.exec",
        },
        {
          id: "codex-exec-patch",
          name: "codex exec patch-hardened",
          family: "codex",
          toolId: "tool.code.codex.exec.patch",
        },
        {
          id: "teddy-exec",
          name: "teddy exec",
          family: "teddy",
          toolId: "tool.code.teddy.exec",
        },
      ],
      matrix: {
        invalid_output: ["codex-exec-patch", "teddy-exec"],
        no_changes: ["codex-exec-patch", "teddy-exec"],
        token_limit: ["codex-exec-patch", "teddy-exec"],
        timeout: ["teddy-exec", "codex-exec-patch"],
        rate_limited: ["teddy-exec", "codex-exec-patch"],
        model_unavailable: ["teddy-exec", "codex-exec-patch"],
        provider_bad_request: ["codex-exec-patch", "teddy-exec"],
        auth_or_permission: ["teddy-exec", "codex-exec-patch"],
        cli_not_found: ["teddy-exec", "codex-exec-patch"],
        nonzero_exit: ["codex-exec-patch", "teddy-exec"],
        unknown: ["codex-exec-patch", "teddy-exec"],
      },
    },
    review: {
      maxAttemptsTotal: 4,
      maxAttemptsPerFamily: 2,
      maxRevisionsPerStrategy: 2,
      forceFamilySwitchErrorKinds: ["auth_or_permission", "cli_not_found", "p0_p1_unresolved"],
      fallbackOrder: ["codex-review-loop-focused", "teddy-review-loop", "codex-review-loop"],
      fallbackOrderOnFamilySwitch: ["teddy-review-loop", "codex-review-loop-focused", "codex-review-loop"],
      nonzeroExitRetry: {
        enabled: true,
        errorKind: "nonzero_exit",
      },
      strategies: [
        {
          id: "codex-review-loop",
          name: "codex review + codex revision",
          family: "codex",
          reviewToolId: "tool.review.codex.review",
          revisionToolId: "tool.review.codex.revision",
        },
        {
          id: "codex-review-loop-focused",
          name: "codex review + codex focused revision",
          family: "codex",
          reviewToolId: "tool.review.codex.review",
          revisionToolId: "tool.review.codex.revision.focused",
        },
        {
          id: "teddy-review-loop",
          name: "teddy review + teddy revision",
          family: "teddy",
          reviewToolId: "tool.review.teddy.review",
          revisionToolId: "tool.review.teddy.revision",
        },
      ],
      matrix: {
        p0_p1_unresolved: ["teddy-review-loop", "codex-review-loop-focused"],
        invalid_output: ["codex-review-loop-focused", "teddy-review-loop"],
        token_limit: ["teddy-review-loop", "codex-review-loop-focused"],
        timeout: ["teddy-review-loop", "codex-review-loop-focused"],
        rate_limited: ["teddy-review-loop", "codex-review-loop-focused"],
        model_unavailable: ["teddy-review-loop", "codex-review-loop-focused"],
        provider_bad_request: ["codex-review-loop-focused", "teddy-review-loop"],
        auth_or_permission: ["teddy-review-loop", "codex-review-loop-focused"],
        cli_not_found: ["teddy-review-loop", "codex-review-loop-focused"],
        nonzero_exit: ["codex-review-loop-focused", "teddy-review-loop"],
        unknown: ["codex-review-loop-focused", "teddy-review-loop"],
      },
    },
    communication: {
      maxAttemptsTotal: 3,
      maxAttemptsPerFamily: 2,
      forceFamilySwitchErrorKinds: ["auth_or_permission", "provider_bad_request", "attachment_unavailable"],
      fallbackOrder: ["email-attachment-aware", "email-semantic"],
      fallbackOrderOnFamilySwitch: ["email-semantic", "email-attachment-aware"],
      nonzeroExitRetry: {
        enabled: false,
        errorKind: "nonzero_exit",
      },
      strategies: [
        {
          id: "email-semantic",
          name: "Email Semantic",
          family: "semantic",
          toolId: "tool.communication.email.semantic",
        },
        {
          id: "email-attachment-aware",
          name: "Email Attachment Aware",
          family: "attachment",
          toolId: "tool.communication.email.attachment",
        },
      ],
      matrix: {
        cli_not_found: ["email-semantic", "email-attachment-aware"],
        auth_or_permission: ["email-semantic", "email-attachment-aware"],
        model_unavailable: ["email-semantic", "email-attachment-aware"],
        token_limit: ["email-semantic", "email-attachment-aware"],
        rate_limited: ["email-semantic", "email-attachment-aware"],
        timeout: ["email-semantic", "email-attachment-aware"],
        provider_bad_request: ["email-semantic", "email-attachment-aware"],
        nonzero_exit: ["email-semantic", "email-attachment-aware"],
        invalid_output: ["email-attachment-aware", "email-semantic"],
        low_confidence: ["email-attachment-aware", "email-semantic"],
        attachment_unavailable: ["email-semantic", "email-attachment-aware"],
        research_failed: ["email-semantic", "email-attachment-aware"],
        unknown: ["email-attachment-aware", "email-semantic"],
      },
    },
  },
} as const;
